<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>Domain Node.js v0.10.26 Manual &amp; Documentation</title>
  <link rel="stylesheet" href="assets/style.css">
  <link rel="stylesheet" href="assets/sh.css">
  <link rel="canonical" href="http://nodejs.org/api/domain.html">
</head>
<body class="alt apidoc" id="api-section-domain">
    <div id="intro" class="interior">
        <a href="/" title="Go back to the home page">
            <img id="logo" src="http://nodejs.org/images/logo-light.png" alt="node.js">
        </a>
    </div>
    <div id="content" class="clearfix">
        <div id="column2" class="interior">
            <ul>
                <!--
                <li><a href="/" class="home">Home</a></li>
                <li><a href="/download/" class="download">Download</a></li>
                <li><a href="/about/" class="about">About</a></li>
                <li><a href="http://npmjs.org/" class="npm">npm Registry</a></li>
                <li><a href="http://nodejs.org/api/" class="docs current">Docs</a></li>
                <li><a href="http://blog.nodejs.org" class="blog">Blog</a></li>
                <li><a href="/community/" class="community">Community</a></li>
                <li><a href="/logos/" class="logos">Logos</a></li>
                -->
               <li><a href="../" class="home">ホーム</a></li>
               <li><a href="../#download" class="download">ダウンロード</a></li>
               <li><a href="../about/" class="about">概要</a></li>
               <li><a href="http://npmjs.org/" class="npm">npm レジストリ</a></li>
               <li><a href="../api/" class="docs current">ドキュメント</a></li>
               <li><a href="http://blog.nodejs.org" class="blog">ブログ</a></li>
               <li><a href="../community/" class="community">コミュニティ</a></li>
               <li><a href="../logos/" class="logos">ロゴ</a></li>
                <li><a href="http://jobs.nodejs.org/" class="jobs">Jobs</a></li>
            </ul>
            <p class="twitter"><a href="http://twitter.com/nodejs">@nodejs</a></p>
        </div>

        <div id="column1" class="interior">
          <header>
            <h1>Node.js v0.10.26 マニュアル &amp; ドキュメンテーション</h1>
            <div id="gtoc">
              <p>
                <a href="index.html" name="toc">Index</a> |
                <a href="all.html">View on single page</a> |
                <a href="domain.json">View as JSON</a>
              </p>
            </div>
            <hr>
          </header>

          <div id="toc">
            <h2>Table of Contents</h2>
            <ul>
<li><a href="#domain_domain">Domain</a><ul>
<li><a href="#domain_warning_don_t_ignore_errors">Warning: Don&#39;t Ignore Errors!</a></li>
<li><a href="#domain_additions_to_error_objects">Additions to Error objects</a></li>
<li><a href="#domain_implicit_binding">Implicit Binding</a></li>
<li><a href="#domain_explicit_binding">Explicit Binding</a></li>
<li><a href="#domain_domain_create">domain.create()</a></li>
<li><a href="#domain_class_domain">Class: Domain</a><ul>
<li><a href="#domain_domain_run_fn">domain.run(fn)</a></li>
<li><a href="#domain_domain_members">domain.members</a></li>
<li><a href="#domain_domain_add_emitter">domain.add(emitter)</a></li>
<li><a href="#domain_domain_remove_emitter">domain.remove(emitter)</a></li>
<li><a href="#domain_domain_bind_callback">domain.bind(callback)</a><ul>
<li><a href="#domain_example">Example</a></li>
</ul>
</li>
<li><a href="#domain_domain_intercept_callback">domain.intercept(callback)</a><ul>
<li><a href="#domain_example_1">Example</a></li>
</ul>
</li>
<li><a href="#domain_domain_enter">domain.enter()</a></li>
<li><a href="#domain_domain_exit">domain.exit()</a></li>
<li><a href="#domain_domain_dispose">domain.dispose()</a></li>
</ul>
</li>
</ul>
</li>
</ul>

          </div>

          <div id="apicontent">
            <h1>Domain<span><a class="mark" href="#domain_domain" id="domain_domain">#</a></span></h1>
<pre class="api_stability_2">Stability: 2 - Unstable</pre><!--
Domains provide a way to handle multiple different IO operations as a
single group.  If any of the event emitters or callbacks registered to a
domain emit an `error` event, or throw an error, then the domain object
will be notified, rather than losing the context of the error in the
`process.on('uncaughtException')` handler, or causing the program to
exit immediately with an error code.
-->

<p>ドメインは複数の異なる I/O 操作を一つのグループとして扱う方法を
提供します。
もし EventEmitter またはコールバックがドメインに登録されると、
<code>&#39;error&#39;</code> がイベントが発生したり例外がスローされた場合、
<code>process.on(&#39;uncaughtException&#39;)</code> ハンドラでエラーのコンテキストが失われたり、
プログラムがエラーコードと共に即座に終了する代わりに、
ドメインオブジェクトに通知されます

</p>
<!--
This feature is new in Node version 0.8.  It is a first pass, and is
expected to change significantly in future versions.  Please use it and
provide feedback.
-->

<p>この機能は Node バージョン 0.8 からの新しいものです。
これはファーストパスであり、将来のバージョンで大きく変更されると予想されます。
是非これを使ってフィードバックをしてください。

</p>
<!--
Due to their experimental nature, the Domains features are disabled unless
the `domain` module is loaded at least once.  No domains are created or
registered by default.  This is by design, to prevent adverse effects on
current programs.  It is expected to be enabled by default in future
Node.js versions.
-->

<p>これらは実験的であるため、ドメインの機能は <code>domain</code> モジュールが少なくとも
一回はロードされるまで無効になっています。
デフォルトではドメインは作成されず、デフォルトで登録もされません。
それは既存のプログラムに悪影響を与えることを防ぐために設計されています。
将来の Node.js バージョンではデフォルトで有効になることが期待されます。

</p>
<h2>Warning: Don&#39;t Ignore Errors!<span><a class="mark" href="#domain_warning_don_t_ignore_errors" id="domain_warning_don_t_ignore_errors">#</a></span></h2>
<!-- type=misc -->

<!--
Domain error handlers are not a substitute for closing down your
process when an error occurs.
-->

<p>ドメインのエラーハンドラは、エラーが発生した時に
プロセスを終了する代わりにはなりません。

</p>
<!--
By the very nature of how `throw` works in JavaScript, there is almost
never any way to safely "pick up where you left off", without leaking
references, or creating some other sort of undefined brittle state.
-->

<p>JavaScript において「throw」がどのように働くかという性質により、
参照のリークや未定義の脆弱な状態を作ることなく「中断したところを取得する」
方法はほとんどありません。

</p>
<!--
The safest way to respond to a thrown error is to shut down the
process.  Of course, in a normal web server, you might have many
connections open, and it is not reasonable to abruptly shut those down
because an error was triggered by someone else.
-->

<p>スローされたエラーに対処するもっとも安全な方法はプロセスを終了することです。
もちろん、通常の Web サーバは多くの接続をオープンしていており、
他の誰かによって引き起こされたエラーのためにそれらをシャットダウンすることは
合理的ではありません。

</p>
<!--
The better approach is send an error response to the request that
triggered the error, while letting the others finish in their normal
time, and stop listening for new requests in that worker.
-->

<p>よりよいアプローチは、エラーを引き起こしたリクエストにエラーを応答し、
それ以外の接続が正常に終了するまでの間、ワーカは新しいリクエストのリスニングを
止めることです。

</p>
<!--
In this way, `domain` usage goes hand-in-hand with the cluster module,
since the master process can fork a new worker when a worker
encounters an error.  For node programs that scale to multiple
machines, the terminating proxy or service registry can take note of
the failure, and react accordingly.
-->

<p>この方法では、<code>domain</code> はクラスタモジュールと手を取り合う利用方法により、
ワーカプロセスがエラーに遭遇した場合に新しいワーカをフォークできます。
複数のマシンにスケールする node プログラムでは、
終端のプロキシやサービスレジストリは障害に注意し、
それに応じて対処することができます。

</p>
<!--
For example, this is not a good idea:
-->

<p>たとえば、これはいいアイディアではありません:

</p>
<pre><code class="javascript">// XXX WARNING!  BAD IDEA!

var d = require(&#39;domain&#39;).create();
d.on(&#39;error&#39;, function(er) {
  // The error won&#39;t crash the process, but what it does is worse!
  // Though we&#39;ve prevented abrupt process restarting, we are leaking
  // resources like crazy if this ever happens.
  // This is no better than process.on(&#39;uncaughtException&#39;)!
  console.log(&#39;error, but oh well&#39;, er.message);
});
d.run(function() {
  require(&#39;http&#39;).createServer(function(req, res) {
    handleRequest(req, res);
  }).listen(PORT);
});</code></pre>
<!--
By using the context of a domain, and the resilience of separating our
program into multiple worker processes, we can react more
appropriately, and handle errors with much greater safety.
-->

<p>domain の利用と、プログラムを複数のワーカプロセスに分割することによる
復元力により、とても安全にエラーを扱う、より適切な対処をすることができます。

</p>
<pre><code class="javascript">// Much better!

var cluster = require(&#39;cluster&#39;);
var PORT = +process.env.PORT || 1337;

if (cluster.isMaster) {
  // In real life, you&#39;d probably use more than just 2 workers,
  // and perhaps not put the master and worker in the same file.
  //
  // You can also of course get a bit fancier about logging, and
  // implement whatever custom logic you need to prevent DoS
  // attacks and other bad behavior.
  //
  // See the options in the cluster documentation.
  //
  // The important thing is that the master does very little,
  // increasing our resilience to unexpected errors.

  cluster.fork();
  cluster.fork();

  cluster.on(&#39;disconnect&#39;, function(worker) {
    console.error(&#39;disconnect!&#39;);
    cluster.fork();
  });

} else {
  // the worker
  //
  // This is where we put our bugs!

  var domain = require(&#39;domain&#39;);

  // See the cluster documentation for more details about using
  // worker processes to serve requests.  How it works, caveats, etc.

  var server = require(&#39;http&#39;).createServer(function(req, res) {
    var d = domain.create();
    d.on(&#39;error&#39;, function(er) {
      console.error(&#39;error&#39;, er.stack);

      // Note: we&#39;re in dangerous territory!
      // By definition, something unexpected occurred,
      // which we probably didn&#39;t want.
      // Anything can happen now!  Be very careful!

      try {
        // make sure we close down within 30 seconds
        var killtimer = setTimeout(function() {
          process.exit(1);
        }, 30000);
        // But don&#39;t keep the process open just for that!
        killtimer.unref();

        // stop taking new requests.
        server.close();

        // Let the master know we&#39;re dead.  This will trigger a
        // &#39;disconnect&#39; in the cluster master, and then it will fork
        // a new worker.
        cluster.worker.disconnect();

        // try to send an error to the request that triggered the problem
        res.statusCode = 500;
        res.setHeader(&#39;content-type&#39;, &#39;text/plain&#39;);
        res.end(&#39;Oops, there was a problem!\n&#39;);
      } catch (er2) {
        // oh well, not much we can do at this point.
        console.error(&#39;Error sending 500!&#39;, er2.stack);
      }
    });

    // Because req and res were created before this domain existed,
    // we need to explicitly add them.
    // See the explanation of implicit vs explicit binding below.
    d.add(req);
    d.add(res);

    // Now run the handler function in the domain.
    d.run(function() {
      handleRequest(req, res);
    });
  });
  server.listen(PORT);
}

// This part isn&#39;t important.  Just an example routing thing.
// You&#39;d put your fancy application logic here.
function handleRequest(req, res) {
  switch(req.url) {
    case &#39;/error&#39;:
      // We do some async stuff, and then...
      setTimeout(function() {
        // Whoops!
        flerb.bark();
      });
      break;
    default:
      res.end(&#39;ok&#39;);
  }
}</code></pre>
<h2>Additions to Error objects<span><a class="mark" href="#domain_additions_to_error_objects" id="domain_additions_to_error_objects">#</a></span></h2>
<!-- type=misc -->

<!--
Any time an Error object is routed through a domain, a few extra fields
are added to it.
-->

<p>どんな場合でも、ドメインに送られた Error オブジェクトは
いくつかのフィールドが加えられます。

</p>
<!--
* `error.domain` The domain that first handled the error.
* `error.domainEmitter` The event emitter that emitted an 'error' event
  with the error object.
* `error.domainBound` The callback function which was bound to the
  domain, and passed an error as its first argument.
* `error.domainThrown` A boolean indicating whether the error was
  thrown, emitted, or passed to a bound callback function.
-->

<ul>
<li><code>error.domain</code> このエラーを最初に捕まえたドメイン。</li>
<li><code>error.domainEmitter</code> このエラーオブジェクトと共に <code>error</code> イベントを
生成した EventEmitter。</li>
<li><code>error.domainBound</code> ドメインに束縛されたコールバック関数で、
その第 1 引数にエラーが渡されたもの。</li>
<li><code>error.domainThrown</code> エラーがスローされたか、EventEmitter から生成されたか、
それとも束縛されたコールバック関数に渡されたかを示す boolean 値。</li>
</ul>
<h2>Implicit Binding<span><a class="mark" href="#domain_implicit_binding" id="domain_implicit_binding">#</a></span></h2>
<!--type=misc-->

<!--
If domains are in use, then all **new** EventEmitter objects (including
Stream objects, requests, responses, etc.) will be implicitly bound to
the active domain at the time of their creation.
-->

<p>一度ドメインが作成されると、全ての <strong>新しい</strong> EventEmitter オブジェクト
(ストリームオブジェクトやリクエスト、レスポンス、その他を含む) は、
それが作成された時点でアクティブなドメインに暗黙的に束縛されます。

</p>
<!--
Additionally, callbacks passed to lowlevel event loop requests (such as
to fs.open, or other callback-taking methods) will automatically be
bound to the active domain.  If they throw, then the domain will catch
the error.
-->

<p>加えて、コールバックが低水準のイベントループ要求 (例えば <code>fs.open()</code>、
あるいは他のコールバックを受け取るメソッド) もアクティブなドメインに
束縛されます。
もしそれらが例外をスローすると、ドメインはそれを捕まえます。

</p>
<!--
In order to prevent excessive memory usage, Domain objects themselves
are not implicitly added as children of the active domain.  If they
were, then it would be too easy to prevent request and response objects
from being properly garbage collected.
-->

<p>必要以上にメモリを消費するのを防ぐため、ドメインオブジェクトそれ自身は
暗黙的にアクティブドメインの子として暗黙的には追加されません。
それをすれば、リクエストやレスポンスオブジェクトがきちんと GC されることを
あまりにも簡単に妨害してしまうでしょう。

</p>
<!--
If you *want* to nest Domain objects as children of a parent Domain,
then you must explicitly add them.
-->

<p>もしネストしたドメインを子として他のドメインに <em>加えたければ</em>
明示的にそれを加えなければなりません。

</p>
<!--
Implicit binding routes thrown errors and `'error'` events to the
Domain's `error` event, but does not register the EventEmitter on the
Domain, so `domain.dispose()` will not shut down the EventEmitter.
Implicit binding only takes care of thrown errors and `'error'` events.
-->

<p>暗黙的なドメインはスローされたエラーや <code>&#39;error&#39;</code> イベントを、
ドメインの <code>&#39;error&#39;</code> イベントにルーティングしますが、
その EventEmitter をドメインに登録しないので、<code>domain.dispose()</code> は
EventEmitter をシャットダウンしません。
暗黙的なバインディングはスローされた例外と <code>&#39;error&#39;</code> イベントにだけ
注意を払います。

</p>
<h2>Explicit Binding<span><a class="mark" href="#domain_explicit_binding" id="domain_explicit_binding">#</a></span></h2>
<!--type=misc-->

<!--
Sometimes, the domain in use is not the one that ought to be used for a
specific event emitter.  Or, the event emitter could have been created
in the context of one domain, but ought to instead be bound to some
other domain.
-->

<p>時には、使用中のドメインは特定の EventEmitter に使用されるべきではありません。
あるいは、EventEmitter はあるドメインのコンテキスト中で作成されますが、
その他のドメインに結びつけられるべきかもしれません。

</p>
<!--
For example, there could be one domain in use for an HTTP server, but
perhaps we would like to have a separate domain to use for each request.
-->

<p>例えば、HTTP サーバで使われるドメインが一つあるとしても、
おそらくリクエスト毎に独立したドメインを持ちたいでしょう。

</p>
<!--
That is possible via explicit binding.
-->

<p>これは明示的なバインディングによって可能となります。

</p>
<!--
For example:
-->

<p>例:

</p>
<pre><code>// create a top-level domain for the server
var serverDomain = domain.create();

serverDomain.run(function() {
  // server is created in the scope of serverDomain
  http.createServer(function(req, res) {
    // req and res are also created in the scope of serverDomain
    // however, we&#39;d prefer to have a separate domain for each request.
    // create it first thing, and add req and res to it.
    var reqd = domain.create();
    reqd.add(req);
    reqd.add(res);
    reqd.on(&#39;error&#39;, function(er) {
      console.error(&#39;Error&#39;, er, req.url);
      try {
        res.writeHead(500);
        res.end(&#39;Error occurred, sorry.&#39;);
      } catch (er) {
        console.error(&#39;Error sending 500&#39;, er, req.url);
      }
    });
  }).listen(1337);
});</code></pre>
<h2>domain.create()<span><a class="mark" href="#domain_domain_create" id="domain_domain_create">#</a></span></h2>
<div class="signature"><ul>
<li>return: <span class="type">Domain</span></li>
</ul></div>
<!--
Returns a new Domain object.
-->

<p>新しいドメインオブジェクトを返します。

</p>
<h2>Class: Domain<span><a class="mark" href="#domain_class_domain" id="domain_class_domain">#</a></span></h2>
<!--
The Domain class encapsulates the functionality of routing errors and
uncaught exceptions to the active Domain object.
-->

<p>ドメインクラスはエラーのルーティングや捕まえられなかった例外をアクティブな
ドメインにルーティングする機能をカプセル化します。

</p>
<!--
Domain is a child class of [EventEmitter][].  To handle the errors that it
catches, listen to its `error` event.
-->

<p>ドメインは <a href="events.html#events_class_events_eventemitter">EventEmitter</a> の子クラスです。
これが捕まえたエラーを扱いたければ、<code>&#39;error&#39;</code> イベントを監視してください。

</p>
<h3>domain.run(fn)<span><a class="mark" href="#domain_domain_run_fn" id="domain_domain_run_fn">#</a></span></h3>
<div class="signature"><ul>
<li><code>fn</code> <span class="type">Function</span></li>
</ul></div>
<!--
Run the supplied function in the context of the domain, implicitly
binding all event emitters, timers, and lowlevel requests that are
created in that context.
-->

<p>与えられた関数をこのドメインのコンテキストで実行します。
このコンテキストで作成される全ての EventEmitter、タイマ、そして低水準の要求は
暗黙的にバインドされます。

</p>
<!--
This is the most basic way to use a domain.
-->

<p>これはドメインを使用するもっとも一般的な方法です。

</p>
<!--
Example:
-->

<p>例:

</p>
<pre><code>var d = domain.create();
d.on(&#39;error&#39;, function(er) {
  console.error(&#39;Caught error!&#39;, er);
});
d.run(function() {
  process.nextTick(function() {
    setTimeout(function() { // simulating some various async stuff
      fs.open(&#39;non-existent file&#39;, &#39;r&#39;, function(er, fd) {
        if (er) throw er;
        // proceed...
      });
    }, 100);
  });
});</code></pre>
<!--
In this example, the `d.on('error')` handler will be triggered, rather
than crashing the program.
-->

<p>この例では、プログラムはクラッシュせずに <code>d.on(&#39;error&#39;)</code> ハンドラが
呼び出されます。

</p>
<h3>domain.members<span><a class="mark" href="#domain_domain_members" id="domain_domain_members">#</a></span></h3>
<div class="signature"><ul>
<li><span class="type">Array</span></li>
</ul></div>
<!--
An array of timers and event emitters that have been explicitly added
to the domain.
-->

<p>このドメインに明示的に加えられたタイマまたは EventEmitter の配列です。

</p>
<h3>domain.add(emitter)<span><a class="mark" href="#domain_domain_add_emitter" id="domain_domain_add_emitter">#</a></span></h3>
<!--
* `emitter` {EventEmitter | Timer} emitter or timer to be added to the domain
-->

<ul>
<li><code>emitter</code> {EventEmitter | Timer} ドメインに加えられる EventEmitter
またはタイマ</li>
</ul>
<!--
Explicitly adds an emitter to the domain.  If any event handlers called by
the emitter throw an error, or if the emitter emits an `error` event, it
will be routed to the domain's `error` event, just like with implicit
binding.
-->

<p>明示的に EventEmitter をドメインに追加します。
この EventEmitter から呼ばれたどのイベントハンドラがエラーをスローしても、
あるいはこの EventEmitter が <code>&#39;error&#39;</code> イベントを発生しても、
暗黙的にバインディングされたのと同様、それはこのドメインの <code>&#39;error</code>&#39;
イベントにルーティングされます。

</p>
<!--
This also works with timers that are returned from `setInterval` and
`setTimeout`.  If their callback function throws, it will be caught by
the domain 'error' handler.
-->

<p>これは同様に <code>setIntervalu</code> および <code>setTimeout</code> から返されるタイマでも
働きます。それらのコールバック関数がエラーをスローすると、それは
ドメインの <code>&#39;error&#39;</code> ハンドに捕まえられます。

</p>
<!--
If the Timer or EventEmitter was already bound to a domain, it is removed
from that one, and bound to this one instead.
-->

<p>もしタイマまたは EventEmitter が既に他のドメインに束縛されていた場合、
それは元のドメインから削除され、代わりにこのドメインに束縛されます。

</p>
<h3>domain.remove(emitter)<span><a class="mark" href="#domain_domain_remove_emitter" id="domain_domain_remove_emitter">#</a></span></h3>
<!--
* `emitter` {EventEmitter | Timer} emitter or timer to be removed from the domain
-->

<ul>
<li><code>emitter</code> {EventEmitter | Timer} このドメインから削除される EventEmitter
またはタイマ</li>
</ul>
<!--
The opposite of `domain.add(emitter)`.  Removes domain handling from the
specified emitter.
-->

<p>これは <code>domain.add(emitter)</code> と対照的です。指定された EventEmitter を
ドメインから削除します。

</p>
<h3>domain.bind(callback)<span><a class="mark" href="#domain_domain_bind_callback" id="domain_domain_bind_callback">#</a></span></h3>
<!--
* `callback` {Function} The callback function
* return: {Function} The bound function
-->

<ul>
<li><code>callback</code> {Function} コールバック関数</li>
<li>return: {Function} 束縛された関数</li>
</ul>
<!--
The returned function will be a wrapper around the supplied callback
function.  When the returned function is called, any errors that are
thrown will be routed to the domain's `error` event.
-->

<p>返される関数は与えられたコールバック関数のラッパーです。
返された関数が呼び出されると、スローされたエラーはドメインの <code>&#39;error&#39;</code>
イベントにルーティングされます。

</p>
<h4>Example<span><a class="mark" href="#domain_example" id="domain_example">#</a></span></h4>
<pre><code>var d = domain.create();

function readSomeFile(filename, cb) {
  fs.readFile(filename, &#39;utf8&#39;, d.bind(function(er, data) {
    // if this throws, it will also be passed to the domain
    return cb(er, data ? JSON.parse(data) : null);
  }));
}

d.on(&#39;error&#39;, function(er) {
  // an error occurred somewhere.
  // if we throw it now, it will crash the program
  // with the normal line number and stack message.
});</code></pre>
<h3>domain.intercept(callback)<span><a class="mark" href="#domain_domain_intercept_callback" id="domain_domain_intercept_callback">#</a></span></h3>
<!--
* `callback` {Function} The callback function
* return: {Function} The intercepted function
-->

<ul>
<li><code>callback</code> {Function} コールバック関数</li>
<li>return: {Function} インターセプトされた関数</li>
</ul>
<!--
This method is almost identical to `domain.bind(callback)`.  However, in
addition to catching thrown errors, it will also intercept `Error`
objects sent as the first argument to the function.
-->

<p>このメソッドはほとんど <code>domain.bind(callback)</code> と同じです。
ただし、スローされたエラーを捕まえることに加えて、関数に渡される最初の引数が
<code>Error</code> オブジェクトの場合もインターセプトします。

</p>
<!--
In this way, the common `if (er) return callback(er);` pattern can be replaced
with a single error handler in a single place.
-->

<p>これは、一般的な <code>if (er) return callback(er);</code> パターンを一カ所で単一の
エラーハンドラに置き換えることができます。

</p>
<h4>Example<span><a class="mark" href="#domain_example_1" id="domain_example_1">#</a></span></h4>
<pre><code>var d = domain.create();

function readSomeFile(filename, cb) {
  fs.readFile(filename, &#39;utf8&#39;, d.intercept(function(data) {
    // note, the first argument is never passed to the
    // callback since it is assumed to be the &#39;Error&#39; argument
    // and thus intercepted by the domain.

    // if this throws, it will also be passed to the domain
    // so the error-handling logic can be moved to the &#39;error&#39;
    // event on the domain instead of being repeated throughout
    // the program.
    return cb(null, JSON.parse(data));
  }));
}

d.on(&#39;error&#39;, function(er) {
  // an error occurred somewhere.
  // if we throw it now, it will crash the program
  // with the normal line number and stack message.
});</code></pre>
<h3>domain.enter()<span><a class="mark" href="#domain_domain_enter" id="domain_domain_enter">#</a></span></h3>
<!--
The `enter` method is plumbing used by the `run`, `bind`, and `intercept`
methods to set the active domain. It sets `domain.active` and `process.domain`
to the domain, and implicitly pushes the domain onto the domain stack managed
by the domain module (see `domain.exit()` for details on the domain stack). The
call to `enter` delimits the beginning of a chain of asynchronous calls and I/O
operations bound to a domain.
-->

<p><code>enter()</code> メソッドは、<code>run()</code>、<code>bind()</code>、そして <code>intercept()</code> メソッドを
アクティブなドメインに結びつけるために使われます。
これは (このドメインオブジェクト、すなわち <code>this</code> を) <code>domain.active</code> および
<code>process.domain</code> を設定し、ドメインモジュールによって管理される
ドメインのスタックに暗黙的に積み上げます (ドメインのスタックに関する詳細は
<code>domain.exit()</code> を参照)。

</p>
<!--
Calling `enter` changes only the active domain, and does not alter the domain
itself. `Enter` and `exit` can be called an arbitrary number of times on a
single domain.
-->

<p><code>enter()</code> の呼び出しはアクティブなドメインを変更することだけで、
ドメイン自身は変化しません。
<code>enter()</code> と <code>exit()</code> は一つのドメインに対して何度でも呼び出すことができます。

</p>
<!--
If the domain on which `enter` is called has been disposed, `enter` will return
without setting the domain.
-->

<p>もし <code>enter()</code> が呼び出されたドメインが破棄済みだと、
<code>enter()</code> は何も設定せずにリターンします。

</p>
<h3>domain.exit()<span><a class="mark" href="#domain_domain_exit" id="domain_domain_exit">#</a></span></h3>
<!--
The `exit` method exits the current domain, popping it off the domain stack.
Any time execution is going to switch to the context of a different chain of
asynchronous calls, it's important to ensure that the current domain is exited.
The call to `exit` delimits either the end of or an interruption to the chain
of asynchronous calls and I/O operations bound to a domain.
-->

<p><code>exit()</code> メソッドは現在のドメインから抜け出し、スタックから取り除きます。
非同期呼び出しのチェーンが異なるコンテキストに切り替わる場合はどんな時でも、
現在のドメインから確実に抜け出すことは重要です。
<code>exit()</code> の呼び出しは、ドメインに束縛された非同期呼び出しおよび
I/O 操作のチェーンを、終端または途中で区切ります。

</p>
<!--
If there are multiple, nested domains bound to the current execution context,
`exit` will exit any domains nested within this domain.
-->

<p>もし複数のネストしたドメインが現在の実行コンテキストに束縛されていると、
<code>exit()</code> はネストしたどのドメインからも抜け出します。

</p>
<!--
Calling `exit` changes only the active domain, and does not alter the domain
itself. `Enter` and `exit` can be called an arbitrary number of times on a
single domain.
-->

<p><code>exit()</code> の呼び出しはアクティブなドメインを変更することだけで、
ドメイン自身は変化しません。
<code>enter()</code> と <code>exit()</code> は一つのドメインに対して何度でも呼び出すことができます。

</p>
<!--
If the domain on which `exit` is called has been disposed, `exit` will return
without exiting the domain.
-->

<p>もし <code>exit()</code> が呼び出されたドメインが破棄済みだと、
<code>exit()</code> は何も設定せずにリターンします。

</p>
<h3>domain.dispose()<span><a class="mark" href="#domain_domain_dispose" id="domain_domain_dispose">#</a></span></h3>
<!--
The dispose method destroys a domain, and makes a best effort attempt to
clean up any and all IO that is associated with the domain.  Streams are
aborted, ended, closed, and/or destroyed.  Timers are cleared.
Explicitly bound callbacks are no longer called.  Any error events that
are raised as a result of this are ignored.
-->

<p><code>dispose()</code> メソッドはドメインを破棄し、ドメインに関連づけられた全ての
I/O を可能な限りクリーンナップしようと試みます。
ストリームはアボートされ、終了され、クローズされ、そして／または破棄されます。
タイマはクリアされます。明示的に束縛されたコールバックはもう呼び出されません。
結果として発生するどんなエラーイベントも無視されます。

</p>
<!--
The intention of calling `dispose` is generally to prevent cascading
errors when a critical part of the Domain context is found to be in an
error state.
-->

<p><code>dispose()</code> を呼び出す意図は通常、エラー状態の中でドメインコンテキストの
クリティカルな部分が見つかった場合に、カスケードしたエラーを防ぐことです。

</p>
<!--
Once the domain is disposed the `dispose` event will emit.
-->

<p>ドメインが破棄されると、<code>&#39;dispose&#39;</code> イベントが生成されます。

</p>
<!--
Note that IO might still be performed.  However, to the highest degree
possible, once a domain is disposed, further errors from the emitters in
that set will be ignored.  So, even if some remaining actions are still
in flight, Node.js will not communicate further about them.
-->

<p>I/O がまだ行われているかもしれないことに注意してください。
しかしながら、可能な限り高い視点から見ると、一度ドメインが破棄されれば、
その集合の中の EventEmitter からのさらなるエラーは無視されます。
そのため、たとえ残りのアクションがまだ実行中だとしても、
Node.js はそれらとコミュニケートしません。

</p>

          </div>
        </div>
    </div>
    <div id="footer">
        <a href="http://joyent.com" class="joyent-logo">Joyent</a>
        <ul class="clearfix">
            <!--
            <li><a href="/">Node.js</a></li>
            <li><a href="/download/">Download</a></li>
            <li><a href="/about/">About</a></li>
            <li><a href="http://npmjs.org/">npm Registry</a></li>
            <li><a href="http://nodejs.org/api/">Docs</a></li>
            <li><a href="http://blog.nodejs.org">Blog</a></li>
            <li><a href="/community/">Community</a></li>
            <li><a href="/logos/">Logos</a></li>
            -->
            <li><a href="../">Node.js</a></li>
            <li><a href="../#download">ダウンロード</a></li>
            <li><a href="../about/">概要</a></li>
            <li><a href="http://npmjs.org/">npm レジストリ</a></li>
            <li><a href="../api/">ドキュメント</a></li>
            <li><a href="http://blog.nodejs.org">ブログ</a></li>
            <li><a href="../community/">コミュニティ</a></li>
            <li><a href="../logos/">ロゴ</a></li>
            <li><a href="http://jobs.nodejs.org/">Jobs</a></li>
            <li><a href="http://twitter.com/nodejs" class="twitter">@nodejs</a></li>
        </ul>

        <p>Copyright <a href="http://joyent.com/">Joyent, Inc</a>, Node.js is a <a href="/trademark-policy.pdf">trademark</a> of Joyent, Inc. View <a href="https://raw.github.com/joyent/node/v0.10.26/LICENSE">license</a>.</p>
    </div>

  <script src="../sh_main.js"></script>
  <script src="../sh_javascript.min.js"></script>
  <script>highlight(undefined, undefined, 'pre');</script>
  <script>
    window._gaq = [['_setAccount', 'UA-10874194-2'], ['_trackPageview']];
    (function(d, t) {
      var g = d.createElement(t),
          s = d.getElementsByTagName(t)[0];
      g.src = '//www.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g, s);
    }(document, 'script'));
  </script>
</body>
</html>

