{
  "source": "doc/api/domain.markdown",
  "modules": [
    {
      "textRaw": "Domain",
      "name": "domain",
      "stability": 2,
      "stabilityText": "Unstable",
      "desc": "<!--\nDomains provide a way to handle multiple different IO operations as a\nsingle group.  If any of the event emitters or callbacks registered to a\ndomain emit an `error` event, or throw an error, then the domain object\nwill be notified, rather than losing the context of the error in the\n`process.on('uncaughtException')` handler, or causing the program to\nexit immediately with an error code.\n-->\n\n<p>ドメインは複数の異なる I/O 操作を一つのグループとして扱う方法を\n提供します。\nもし EventEmitter またはコールバックがドメインに登録されると、\n<code>&#39;error&#39;</code> がイベントが発生したり例外がスローされた場合、\n<code>process.on(&#39;uncaughtException&#39;)</code> ハンドラでエラーのコンテキストが失われたり、\nプログラムがエラーコードと共に即座に終了する代わりに、\nドメインオブジェクトに通知されます\n\n</p>\n<!--\nThis feature is new in Node version 0.8.  It is a first pass, and is\nexpected to change significantly in future versions.  Please use it and\nprovide feedback.\n-->\n\n<p>この機能は Node バージョン 0.8 からの新しいものです。\nこれはファーストパスであり、将来のバージョンで大きく変更されると予想されます。\n是非これを使ってフィードバックをしてください。\n\n</p>\n<!--\nDue to their experimental nature, the Domains features are disabled unless\nthe `domain` module is loaded at least once.  No domains are created or\nregistered by default.  This is by design, to prevent adverse effects on\ncurrent programs.  It is expected to be enabled by default in future\nNode.js versions.\n-->\n\n<p>これらは実験的であるため、ドメインの機能は <code>domain</code> モジュールが少なくとも\n一回はロードされるまで無効になっています。\nデフォルトではドメインは作成されず、デフォルトで登録もされません。\nそれは既存のプログラムに悪影響を与えることを防ぐために設計されています。\n将来の Node.js バージョンではデフォルトで有効になることが期待されます。\n\n</p>\n",
      "miscs": [
        {
          "textRaw": "Warning: Don't Ignore Errors!",
          "name": "Warning: Don't Ignore Errors!",
          "type": "misc",
          "desc": "<!--\nDomain error handlers are not a substitute for closing down your\nprocess when an error occurs.\n-->\n\n<p>ドメインのエラーハンドラは、エラーが発生した時に\nプロセスを終了する代わりにはなりません。\n\n</p>\n<!--\nBy the very nature of how `throw` works in JavaScript, there is almost\nnever any way to safely \"pick up where you left off\", without leaking\nreferences, or creating some other sort of undefined brittle state.\n-->\n\n<p>JavaScript において「throw」がどのように働くかという性質により、\n参照のリークや未定義の脆弱な状態を作ることなく「中断したところを取得する」\n方法はほとんどありません。\n\n</p>\n<!--\nThe safest way to respond to a thrown error is to shut down the\nprocess.  Of course, in a normal web server, you might have many\nconnections open, and it is not reasonable to abruptly shut those down\nbecause an error was triggered by someone else.\n-->\n\n<p>スローされたエラーに対処するもっとも安全な方法はプロセスを終了することです。\nもちろん、通常の Web サーバは多くの接続をオープンしていており、\n他の誰かによって引き起こされたエラーのためにそれらをシャットダウンすることは\n合理的ではありません。\n\n</p>\n<!--\nThe better approach is send an error response to the request that\ntriggered the error, while letting the others finish in their normal\ntime, and stop listening for new requests in that worker.\n-->\n\n<p>よりよいアプローチは、エラーを引き起こしたリクエストにエラーを応答し、\nそれ以外の接続が正常に終了するまでの間、ワーカは新しいリクエストのリスニングを\n止めることです。\n\n</p>\n<!--\nIn this way, `domain` usage goes hand-in-hand with the cluster module,\nsince the master process can fork a new worker when a worker\nencounters an error.  For node programs that scale to multiple\nmachines, the terminating proxy or service registry can take note of\nthe failure, and react accordingly.\n-->\n\n<p>この方法では、<code>domain</code> はクラスタモジュールと手を取り合う利用方法により、\nワーカプロセスがエラーに遭遇した場合に新しいワーカをフォークできます。\n複数のマシンにスケールする node プログラムでは、\n終端のプロキシやサービスレジストリは障害に注意し、\nそれに応じて対処することができます。\n\n</p>\n<!--\nFor example, this is not a good idea:\n-->\n\n<p>たとえば、これはいいアイディアではありません:\n\n</p>\n<pre><code class="\"javascript\"">// XXX WARNING!  BAD IDEA!\n\nvar d = require(&#39;domain&#39;).create();\nd.on(&#39;error&#39;, function(er) {\n  // The error won&#39;t crash the process, but what it does is worse!\n  // Though we&#39;ve prevented abrupt process restarting, we are leaking\n  // resources like crazy if this ever happens.\n  // This is no better than process.on(&#39;uncaughtException&#39;)!\n  console.log(&#39;error, but oh well&#39;, er.message);\n});\nd.run(function() {\n  require(&#39;http&#39;).createServer(function(req, res) {\n    handleRequest(req, res);\n  }).listen(PORT);\n});</code></pre>\n<!--\nBy using the context of a domain, and the resilience of separating our\nprogram into multiple worker processes, we can react more\nappropriately, and handle errors with much greater safety.\n-->\n\n<p>domain の利用と、プログラムを複数のワーカプロセスに分割することによる\n復元力により、とても安全にエラーを扱う、より適切な対処をすることができます。\n\n</p>\n<pre><code class="\"javascript\"">// Much better!\n\nvar cluster = require(&#39;cluster&#39;);\nvar PORT = +process.env.PORT || 1337;\n\nif (cluster.isMaster) {\n  // In real life, you&#39;d probably use more than just 2 workers,\n  // and perhaps not put the master and worker in the same file.\n  //\n  // You can also of course get a bit fancier about logging, and\n  // implement whatever custom logic you need to prevent DoS\n  // attacks and other bad behavior.\n  //\n  // See the options in the cluster documentation.\n  //\n  // The important thing is that the master does very little,\n  // increasing our resilience to unexpected errors.\n\n  cluster.fork();\n  cluster.fork();\n\n  cluster.on(&#39;disconnect&#39;, function(worker) {\n    console.error(&#39;disconnect!&#39;);\n    cluster.fork();\n  });\n\n} else {\n  // the worker\n  //\n  // This is where we put our bugs!\n\n  var domain = require(&#39;domain&#39;);\n\n  // See the cluster documentation for more details about using\n  // worker processes to serve requests.  How it works, caveats, etc.\n\n  var server = require(&#39;http&#39;).createServer(function(req, res) {\n    var d = domain.create();\n    d.on(&#39;error&#39;, function(er) {\n      console.error(&#39;error&#39;, er.stack);\n\n      // Note: we&#39;re in dangerous territory!\n      // By definition, something unexpected occurred,\n      // which we probably didn&#39;t want.\n      // Anything can happen now!  Be very careful!\n\n      try {\n        // make sure we close down within 30 seconds\n        var killtimer = setTimeout(function() {\n          process.exit(1);\n        }, 30000);\n        // But don&#39;t keep the process open just for that!\n        killtimer.unref();\n\n        // stop taking new requests.\n        server.close();\n\n        // Let the master know we&#39;re dead.  This will trigger a\n        // &#39;disconnect&#39; in the cluster master, and then it will fork\n        // a new worker.\n        cluster.worker.disconnect();\n\n        // try to send an error to the request that triggered the problem\n        res.statusCode = 500;\n        res.setHeader(&#39;content-type&#39;, &#39;text/plain&#39;);\n        res.end(&#39;Oops, there was a problem!\\n&#39;);\n      } catch (er2) {\n        // oh well, not much we can do at this point.\n        console.error(&#39;Error sending 500!&#39;, er2.stack);\n      }\n    });\n\n    // Because req and res were created before this domain existed,\n    // we need to explicitly add them.\n    // See the explanation of implicit vs explicit binding below.\n    d.add(req);\n    d.add(res);\n\n    // Now run the handler function in the domain.\n    d.run(function() {\n      handleRequest(req, res);\n    });\n  });\n  server.listen(PORT);\n}\n\n// This part isn&#39;t important.  Just an example routing thing.\n// You&#39;d put your fancy application logic here.\nfunction handleRequest(req, res) {\n  switch(req.url) {\n    case &#39;/error&#39;:\n      // We do some async stuff, and then...\n      setTimeout(function() {\n        // Whoops!\n        flerb.bark();\n      });\n      break;\n    default:\n      res.end(&#39;ok&#39;);\n  }\n}</code></pre>\n"
        },
        {
          "textRaw": "Additions to Error objects",
          "name": "Additions to Error objects",
          "type": "misc",
          "desc": "<!--\nAny time an Error object is routed through a domain, a few extra fields\nare added to it.\n-->\n\n<p>どんな場合でも、ドメインに送られた Error オブジェクトは\nいくつかのフィールドが加えられます。\n\n</p>\n<!--\n* `error.domain` The domain that first handled the error.\n* `error.domainEmitter` The event emitter that emitted an 'error' event\n  with the error object.\n* `error.domainBound` The callback function which was bound to the\n  domain, and passed an error as its first argument.\n* `error.domainThrown` A boolean indicating whether the error was\n  thrown, emitted, or passed to a bound callback function.\n-->\n\n<ul>\n<li><code>error.domain</code> このエラーを最初に捕まえたドメイン。</li>\n<li><code>error.domainEmitter</code> このエラーオブジェクトと共に <code>error</code> イベントを\n生成した EventEmitter。</li>\n<li><code>error.domainBound</code> ドメインに束縛されたコールバック関数で、\nその第 1 引数にエラーが渡されたもの。</li>\n<li><code>error.domainThrown</code> エラーがスローされたか、EventEmitter から生成されたか、\nそれとも束縛されたコールバック関数に渡されたかを示す boolean 値。</li>\n</ul>\n"
        },
        {
          "textRaw": "Implicit Binding",
          "name": "Implicit Binding",
          "type": "misc",
          "desc": "<!--\nIf domains are in use, then all **new** EventEmitter objects (including\nStream objects, requests, responses, etc.) will be implicitly bound to\nthe active domain at the time of their creation.\n-->\n\n<p>一度ドメインが作成されると、全ての <strong>新しい</strong> EventEmitter オブジェクト\n(ストリームオブジェクトやリクエスト、レスポンス、その他を含む) は、\nそれが作成された時点でアクティブなドメインに暗黙的に束縛されます。\n\n</p>\n<!--\nAdditionally, callbacks passed to lowlevel event loop requests (such as\nto fs.open, or other callback-taking methods) will automatically be\nbound to the active domain.  If they throw, then the domain will catch\nthe error.\n-->\n\n<p>加えて、コールバックが低水準のイベントループ要求 (例えば <code>fs.open()</code>、\nあるいは他のコールバックを受け取るメソッド) もアクティブなドメインに\n束縛されます。\nもしそれらが例外をスローすると、ドメインはそれを捕まえます。\n\n</p>\n<!--\nIn order to prevent excessive memory usage, Domain objects themselves\nare not implicitly added as children of the active domain.  If they\nwere, then it would be too easy to prevent request and response objects\nfrom being properly garbage collected.\n-->\n\n<p>必要以上にメモリを消費するのを防ぐため、ドメインオブジェクトそれ自身は\n暗黙的にアクティブドメインの子として暗黙的には追加されません。\nそれをすれば、リクエストやレスポンスオブジェクトがきちんと GC されることを\nあまりにも簡単に妨害してしまうでしょう。\n\n</p>\n<!--\nIf you *want* to nest Domain objects as children of a parent Domain,\nthen you must explicitly add them.\n-->\n\n<p>もしネストしたドメインを子として他のドメインに <em>加えたければ</em>\n明示的にそれを加えなければなりません。\n\n</p>\n<!--\nImplicit binding routes thrown errors and `'error'` events to the\nDomain's `error` event, but does not register the EventEmitter on the\nDomain, so `domain.dispose()` will not shut down the EventEmitter.\nImplicit binding only takes care of thrown errors and `'error'` events.\n-->\n\n<p>暗黙的なドメインはスローされたエラーや <code>&#39;error&#39;</code> イベントを、\nドメインの <code>&#39;error&#39;</code> イベントにルーティングしますが、\nその EventEmitter をドメインに登録しないので、<code>domain.dispose()</code> は\nEventEmitter をシャットダウンしません。\n暗黙的なバインディングはスローされた例外と <code>&#39;error&#39;</code> イベントにだけ\n注意を払います。\n\n</p>\n"
        },
        {
          "textRaw": "Explicit Binding",
          "name": "Explicit Binding",
          "type": "misc",
          "desc": "<!--\nSometimes, the domain in use is not the one that ought to be used for a\nspecific event emitter.  Or, the event emitter could have been created\nin the context of one domain, but ought to instead be bound to some\nother domain.\n-->\n\n<p>時には、使用中のドメインは特定の EventEmitter に使用されるべきではありません。\nあるいは、EventEmitter はあるドメインのコンテキスト中で作成されますが、\nその他のドメインに結びつけられるべきかもしれません。\n\n</p>\n<!--\nFor example, there could be one domain in use for an HTTP server, but\nperhaps we would like to have a separate domain to use for each request.\n-->\n\n<p>例えば、HTTP サーバで使われるドメインが一つあるとしても、\nおそらくリクエスト毎に独立したドメインを持ちたいでしょう。\n\n</p>\n<!--\nThat is possible via explicit binding.\n-->\n\n<p>これは明示的なバインディングによって可能となります。\n\n</p>\n<!--\nFor example:\n-->\n\n<p>例:\n\n</p>\n<pre><code>// create a top-level domain for the server\nvar serverDomain = domain.create();\n\nserverDomain.run(function() {\n  // server is created in the scope of serverDomain\n  http.createServer(function(req, res) {\n    // req and res are also created in the scope of serverDomain\n    // however, we&#39;d prefer to have a separate domain for each request.\n    // create it first thing, and add req and res to it.\n    var reqd = domain.create();\n    reqd.add(req);\n    reqd.add(res);\n    reqd.on(&#39;error&#39;, function(er) {\n      console.error(&#39;Error&#39;, er, req.url);\n      try {\n        res.writeHead(500);\n        res.end(&#39;Error occurred, sorry.&#39;);\n      } catch (er) {\n        console.error(&#39;Error sending 500&#39;, er, req.url);\n      }\n    });\n  }).listen(1337);\n});</code></pre>\n"
        }
      ],
      "methods": [
        {
          "textRaw": "domain.create()",
          "type": "method",
          "name": "create",
          "signatures": [
            {
              "return": {
                "textRaw": "return: {Domain} ",
                "name": "return",
                "type": "Domain"
              },
              "params": []
            },
            {
              "params": []
            }
          ],
          "desc": "<!--\nReturns a new Domain object.\n-->\n\n<p>新しいドメインオブジェクトを返します。\n\n</p>\n"
        }
      ],
      "classes": [
        {
          "textRaw": "Class: Domain",
          "type": "class",
          "name": "Domain",
          "desc": "<!--\nThe Domain class encapsulates the functionality of routing errors and\nuncaught exceptions to the active Domain object.\n-->\n\n<p>ドメインクラスはエラーのルーティングや捕まえられなかった例外をアクティブな\nドメインにルーティングする機能をカプセル化します。\n\n</p>\n<!--\nDomain is a child class of [EventEmitter][].  To handle the errors that it\ncatches, listen to its `error` event.\n-->\n\n<p>ドメインは [EventEmitter][] の子クラスです。\nこれが捕まえたエラーを扱いたければ、<code>&#39;error&#39;</code> イベントを監視してください。\n\n</p>\n",
          "methods": [
            {
              "textRaw": "domain.run(fn)",
              "type": "method",
              "name": "run",
              "signatures": [
                {
                  "params": [
                    {
                      "textRaw": "`fn` {Function} ",
                      "name": "fn",
                      "type": "Function"
                    }
                  ]
                },
                {
                  "params": [
                    {
                      "name": "fn"
                    }
                  ]
                }
              ],
              "desc": "<!--\nRun the supplied function in the context of the domain, implicitly\nbinding all event emitters, timers, and lowlevel requests that are\ncreated in that context.\n-->\n\n<p>与えられた関数をこのドメインのコンテキストで実行します。\nこのコンテキストで作成される全ての EventEmitter、タイマ、そして低水準の要求は\n暗黙的にバインドされます。\n\n</p>\n<!--\nThis is the most basic way to use a domain.\n-->\n\n<p>これはドメインを使用するもっとも一般的な方法です。\n\n</p>\n<!--\nExample:\n-->\n\n<p>例:\n\n</p>\n<pre><code>var d = domain.create();\nd.on(&#39;error&#39;, function(er) {\n  console.error(&#39;Caught error!&#39;, er);\n});\nd.run(function() {\n  process.nextTick(function() {\n    setTimeout(function() { // simulating some various async stuff\n      fs.open(&#39;non-existent file&#39;, &#39;r&#39;, function(er, fd) {\n        if (er) throw er;\n        // proceed...\n      });\n    }, 100);\n  });\n});</code></pre>\n<!--\nIn this example, the `d.on('error')` handler will be triggered, rather\nthan crashing the program.\n-->\n\n<p>この例では、プログラムはクラッシュせずに <code>d.on(&#39;error&#39;)</code> ハンドラが\n呼び出されます。\n\n</p>\n"
            },
            {
              "textRaw": "domain.add(emitter)",
              "type": "method",
              "name": "add",
              "desc": "<!--\n* `emitter` {EventEmitter | Timer} emitter or timer to be added to the domain\n-->\n\n<ul>\n<li><code>emitter</code> {EventEmitter | Timer} ドメインに加えられる EventEmitter\nまたはタイマ</li>\n</ul>\n<!--\nExplicitly adds an emitter to the domain.  If any event handlers called by\nthe emitter throw an error, or if the emitter emits an `error` event, it\nwill be routed to the domain's `error` event, just like with implicit\nbinding.\n-->\n\n<p>明示的に EventEmitter をドメインに追加します。\nこの EventEmitter から呼ばれたどのイベントハンドラがエラーをスローしても、\nあるいはこの EventEmitter が <code>&#39;error&#39;</code> イベントを発生しても、\n暗黙的にバインディングされたのと同様、それはこのドメインの <code>&#39;error</code>&#39;\nイベントにルーティングされます。\n\n</p>\n<!--\nThis also works with timers that are returned from `setInterval` and\n`setTimeout`.  If their callback function throws, it will be caught by\nthe domain 'error' handler.\n-->\n\n<p>これは同様に <code>setIntervalu</code> および <code>setTimeout</code> から返されるタイマでも\n働きます。それらのコールバック関数がエラーをスローすると、それは\nドメインの <code>&#39;error&#39;</code> ハンドに捕まえられます。\n\n</p>\n<!--\nIf the Timer or EventEmitter was already bound to a domain, it is removed\nfrom that one, and bound to this one instead.\n-->\n\n<p>もしタイマまたは EventEmitter が既に他のドメインに束縛されていた場合、\nそれは元のドメインから削除され、代わりにこのドメインに束縛されます。\n\n</p>\n",
              "signatures": [
                {
                  "params": [
                    {
                      "name": "emitter"
                    }
                  ]
                }
              ]
            },
            {
              "textRaw": "domain.remove(emitter)",
              "type": "method",
              "name": "remove",
              "desc": "<!--\n* `emitter` {EventEmitter | Timer} emitter or timer to be removed from the domain\n-->\n\n<ul>\n<li><code>emitter</code> {EventEmitter | Timer} このドメインから削除される EventEmitter\nまたはタイマ</li>\n</ul>\n<!--\nThe opposite of `domain.add(emitter)`.  Removes domain handling from the\nspecified emitter.\n-->\n\n<p>これは <code>domain.add(emitter)</code> と対照的です。指定された EventEmitter を\nドメインから削除します。\n\n</p>\n",
              "signatures": [
                {
                  "params": [
                    {
                      "name": "emitter"
                    }
                  ]
                }
              ]
            },
            {
              "textRaw": "domain.bind(callback)",
              "type": "method",
              "name": "bind",
              "desc": "<!--\n* `callback` {Function} The callback function\n* return: {Function} The bound function\n-->\n\n<ul>\n<li><code>callback</code> {Function} コールバック関数</li>\n<li>return: {Function} 束縛された関数</li>\n</ul>\n<!--\nThe returned function will be a wrapper around the supplied callback\nfunction.  When the returned function is called, any errors that are\nthrown will be routed to the domain's `error` event.\n-->\n\n<p>返される関数は与えられたコールバック関数のラッパーです。\n返された関数が呼び出されると、スローされたエラーはドメインの <code>&#39;error&#39;</code>\nイベントにルーティングされます。\n\n</p>\n<h4>Example</h4>\n<pre><code>var d = domain.create();\n\nfunction readSomeFile(filename, cb) {\n  fs.readFile(filename, &#39;utf8&#39;, d.bind(function(er, data) {\n    // if this throws, it will also be passed to the domain\n    return cb(er, data ? JSON.parse(data) : null);\n  }));\n}\n\nd.on(&#39;error&#39;, function(er) {\n  // an error occurred somewhere.\n  // if we throw it now, it will crash the program\n  // with the normal line number and stack message.\n});</code></pre>\n",
              "signatures": [
                {
                  "params": [
                    {
                      "name": "callback"
                    }
                  ]
                }
              ]
            },
            {
              "textRaw": "domain.intercept(callback)",
              "type": "method",
              "name": "intercept",
              "desc": "<!--\n* `callback` {Function} The callback function\n* return: {Function} The intercepted function\n-->\n\n<ul>\n<li><code>callback</code> {Function} コールバック関数</li>\n<li>return: {Function} インターセプトされた関数</li>\n</ul>\n<!--\nThis method is almost identical to `domain.bind(callback)`.  However, in\naddition to catching thrown errors, it will also intercept `Error`\nobjects sent as the first argument to the function.\n-->\n\n<p>このメソッドはほとんど <code>domain.bind(callback)</code> と同じです。\nただし、スローされたエラーを捕まえることに加えて、関数に渡される最初の引数が\n<code>Error</code> オブジェクトの場合もインターセプトします。\n\n</p>\n<!--\nIn this way, the common `if (er) return callback(er);` pattern can be replaced\nwith a single error handler in a single place.\n-->\n\n<p>これは、一般的な <code>if (er) return callback(er);</code> パターンを一カ所で単一の\nエラーハンドラに置き換えることができます。\n\n</p>\n<h4>Example</h4>\n<pre><code>var d = domain.create();\n\nfunction readSomeFile(filename, cb) {\n  fs.readFile(filename, &#39;utf8&#39;, d.intercept(function(data) {\n    // note, the first argument is never passed to the\n    // callback since it is assumed to be the &#39;Error&#39; argument\n    // and thus intercepted by the domain.\n\n    // if this throws, it will also be passed to the domain\n    // so the error-handling logic can be moved to the &#39;error&#39;\n    // event on the domain instead of being repeated throughout\n    // the program.\n    return cb(null, JSON.parse(data));\n  }));\n}\n\nd.on(&#39;error&#39;, function(er) {\n  // an error occurred somewhere.\n  // if we throw it now, it will crash the program\n  // with the normal line number and stack message.\n});</code></pre>\n",
              "signatures": [
                {
                  "params": [
                    {
                      "name": "callback"
                    }
                  ]
                }
              ]
            },
            {
              "textRaw": "domain.enter()",
              "type": "method",
              "name": "enter",
              "desc": "<!--\nThe `enter` method is plumbing used by the `run`, `bind`, and `intercept`\nmethods to set the active domain. It sets `domain.active` and `process.domain`\nto the domain, and implicitly pushes the domain onto the domain stack managed\nby the domain module (see `domain.exit()` for details on the domain stack). The\ncall to `enter` delimits the beginning of a chain of asynchronous calls and I/O\noperations bound to a domain.\n-->\n\n<p><code>enter()</code> メソッドは、<code>run()</code>、<code>bind()</code>、そして <code>intercept()</code> メソッドを\nアクティブなドメインに結びつけるために使われます。\nこれは (このドメインオブジェクト、すなわち <code>this</code> を) <code>domain.active</code> および\n<code>process.domain</code> を設定し、ドメインモジュールによって管理される\nドメインのスタックに暗黙的に積み上げます (ドメインのスタックに関する詳細は\n<code>domain.exit()</code> を参照)。\n\n</p>\n<!--\nCalling `enter` changes only the active domain, and does not alter the domain\nitself. `Enter` and `exit` can be called an arbitrary number of times on a\nsingle domain.\n-->\n\n<p><code>enter()</code> の呼び出しはアクティブなドメインを変更することだけで、\nドメイン自身は変化しません。\n<code>enter()</code> と <code>exit()</code> は一つのドメインに対して何度でも呼び出すことができます。\n\n</p>\n<!--\nIf the domain on which `enter` is called has been disposed, `enter` will return\nwithout setting the domain.\n-->\n\n<p>もし <code>enter()</code> が呼び出されたドメインが破棄済みだと、\n<code>enter()</code> は何も設定せずにリターンします。\n\n</p>\n",
              "signatures": [
                {
                  "params": []
                }
              ]
            },
            {
              "textRaw": "domain.exit()",
              "type": "method",
              "name": "exit",
              "desc": "<!--\nThe `exit` method exits the current domain, popping it off the domain stack.\nAny time execution is going to switch to the context of a different chain of\nasynchronous calls, it's important to ensure that the current domain is exited.\nThe call to `exit` delimits either the end of or an interruption to the chain\nof asynchronous calls and I/O operations bound to a domain.\n-->\n\n<p><code>exit()</code> メソッドは現在のドメインから抜け出し、スタックから取り除きます。\n非同期呼び出しのチェーンが異なるコンテキストに切り替わる場合はどんな時でも、\n現在のドメインから確実に抜け出すことは重要です。\n<code>exit()</code> の呼び出しは、ドメインに束縛された非同期呼び出しおよび\nI/O 操作のチェーンを、終端または途中で区切ります。\n\n</p>\n<!--\nIf there are multiple, nested domains bound to the current execution context,\n`exit` will exit any domains nested within this domain.\n-->\n\n<p>もし複数のネストしたドメインが現在の実行コンテキストに束縛されていると、\n<code>exit()</code> はネストしたどのドメインからも抜け出します。\n\n</p>\n<!--\nCalling `exit` changes only the active domain, and does not alter the domain\nitself. `Enter` and `exit` can be called an arbitrary number of times on a\nsingle domain.\n-->\n\n<p><code>exit()</code> の呼び出しはアクティブなドメインを変更することだけで、\nドメイン自身は変化しません。\n<code>enter()</code> と <code>exit()</code> は一つのドメインに対して何度でも呼び出すことができます。\n\n</p>\n<!--\nIf the domain on which `exit` is called has been disposed, `exit` will return\nwithout exiting the domain.\n-->\n\n<p>もし <code>exit()</code> が呼び出されたドメインが破棄済みだと、\n<code>exit()</code> は何も設定せずにリターンします。\n\n</p>\n",
              "signatures": [
                {
                  "params": []
                }
              ]
            },
            {
              "textRaw": "domain.dispose()",
              "type": "method",
              "name": "dispose",
              "desc": "<!--\nThe dispose method destroys a domain, and makes a best effort attempt to\nclean up any and all IO that is associated with the domain.  Streams are\naborted, ended, closed, and/or destroyed.  Timers are cleared.\nExplicitly bound callbacks are no longer called.  Any error events that\nare raised as a result of this are ignored.\n-->\n\n<p><code>dispose()</code> メソッドはドメインを破棄し、ドメインに関連づけられた全ての\nI/O を可能な限りクリーンナップしようと試みます。\nストリームはアボートされ、終了され、クローズされ、そして／または破棄されます。\nタイマはクリアされます。明示的に束縛されたコールバックはもう呼び出されません。\n結果として発生するどんなエラーイベントも無視されます。\n\n</p>\n<!--\nThe intention of calling `dispose` is generally to prevent cascading\nerrors when a critical part of the Domain context is found to be in an\nerror state.\n-->\n\n<p><code>dispose()</code> を呼び出す意図は通常、エラー状態の中でドメインコンテキストの\nクリティカルな部分が見つかった場合に、カスケードしたエラーを防ぐことです。\n\n</p>\n<!--\nOnce the domain is disposed the `dispose` event will emit.\n-->\n\n<p>ドメインが破棄されると、<code>&#39;dispose&#39;</code> イベントが生成されます。\n\n</p>\n<!--\nNote that IO might still be performed.  However, to the highest degree\npossible, once a domain is disposed, further errors from the emitters in\nthat set will be ignored.  So, even if some remaining actions are still\nin flight, Node.js will not communicate further about them.\n-->\n\n<p>I/O がまだ行われているかもしれないことに注意してください。\nしかしながら、可能な限り高い視点から見ると、一度ドメインが破棄されれば、\nその集合の中の EventEmitter からのさらなるエラーは無視されます。\nそのため、たとえ残りのアクションがまだ実行中だとしても、\nNode.js はそれらとコミュニケートしません。\n\n</p>\n",
              "signatures": [
                {
                  "params": []
                }
              ]
            }
          ],
          "properties": [
            {
              "textRaw": "`members` {Array} ",
              "name": "members",
              "desc": "<!--\nAn array of timers and event emitters that have been explicitly added\nto the domain.\n-->\n\n<p>このドメインに明示的に加えられたタイマまたは EventEmitter の配列です。\n\n</p>\n"
            }
          ]
        }
      ],
      "type": "module",
      "displayName": "Domain"
    }
  ]
}
